import {
  InfrastructureArchitecture,
  SimulationResult,
  ArchitectureDecisionRecord,
} from '../types/infrastructure';

export function generateTerraformHcl(arch: InfrastructureArchitecture, sim: SimulationResult): string {
  return `# ==============================================================================
# Terraform HCL - Generated by InfraWeave Infrastructure Blueprint
# Architecture: ${arch.name}
# Simulated Monthly Spend: $${sim.cost.monthlyTotal.toLocaleString()}
# Target Composite Availability: ${sim.reliability.compositeAvailabilityPct}%
# ==============================================================================

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "${arch.regions[0]?.code || 'us-east-1'}"
  default_tags {
    tags = {
      ManagedBy   = "InfraWeave"
      Environment = "production"
      Architecture = "${arch.id}"
    }
  }
}

# ------------------------------------------------------------------------------
# 1. COMPUTE TIER (Auto Scaling & Launch Templates)
# ------------------------------------------------------------------------------
${arch.computeNodes
  .map(
    node => `
resource "aws_autoscaling_group" "${node.id.replace(/-/g, '_')}_asg" {
  name                = "${node.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}-asg"
  min_size            = ${Math.max(1, Math.floor(node.instances * 0.75))}
  max_size            = ${Math.ceil(node.instances * 2.0)}
  desired_capacity    = ${node.instances}
  vpc_zone_identifier = ["subnet-private-a", "subnet-private-b"]

  target_group_arns = [aws_lb_target_group.${node.id.replace(/-/g, '_')}_tg.arn]

  launch_template {
    id      = aws_launch_template.${node.id.replace(/-/g, '_')}_lt.id
    version = "$Latest"
  }

  tag {
    key                 = "Name"
    value               = "${node.name}"
    propagate_at_launch = true
  }
}

resource "aws_launch_template" "${node.id.replace(/-/g, '_')}_lt" {
  name_prefix   = "${node.id.replace(/-/g, '_')}-"
  instance_type = "${node.vCpuPerInstance >= 16 ? 'c6i.4xlarge' : node.vCpuPerInstance >= 8 ? 'c6i.2xlarge' : 'c6i.xlarge'}"

  monitoring {
    enabled = true
  }
}

resource "aws_lb_target_group" "${node.id.replace(/-/g, '_')}_tg" {
  name     = "${node.id.substring(0, 24)}-tg"
  port     = 8080
  protocol = "HTTP"
  vpc_id   = "vpc-production-main"

  health_check {
    path                = "/healthz"
    matcher             = "200"
    interval            = 15
    timeout             = 5
    healthy_threshold   = 2
    unhealthy_threshold = 3
  }
}
`
  )
  .join('\n')}

# ------------------------------------------------------------------------------
# 2. DATABASE TIER (Amazon Aurora PostgreSQL / Distributed Cluster)
# ------------------------------------------------------------------------------
${arch.databaseNodes
  .map(
    db => `
resource "aws_rds_cluster" "${db.id.replace(/-/g, '_')}_cluster" {
  cluster_identifier      = "${db.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}-cluster"
  engine                  = "aurora-postgresql"
  engine_version          = "16.1"
  database_name           = "appdb"
  master_username         = "infraweave_admin"
  manage_master_user_password = true

  backup_retention_period = 30
  preferred_backup_window = "02:00-03:00"
  storage_encrypted       = true
  deletion_protection     = true
}

resource "aws_rds_cluster_instance" "${db.id.replace(/-/g, '_')}_primary" {
  identifier         = "${db.id.replace(/-/g, '_')}-primary"
  cluster_identifier = aws_rds_cluster.${db.id.replace(/-/g, '_')}_cluster.id
  instance_class     = "${db.iopsProvisioned >= 10000 ? 'db.r6g.4xlarge' : 'db.r6g.2xlarge'}"
  engine             = aws_rds_cluster.${db.id.replace(/-/g, '_')}_cluster.engine
}

${Array.from({ length: db.readReplicas })
  .map(
    (_, i) => `
resource "aws_rds_cluster_instance" "${db.id.replace(/-/g, '_')}_replica_${i + 1}" {
  identifier         = "${db.id.replace(/-/g, '_')}-replica-${i + 1}"
  cluster_identifier = aws_rds_cluster.${db.id.replace(/-/g, '_')}_cluster.id
  instance_class     = "${db.iopsProvisioned >= 10000 ? 'db.r6g.4xlarge' : 'db.r6g.2xlarge'}"
  engine             = aws_rds_cluster.${db.id.replace(/-/g, '_')}_cluster.engine
}
`
  )
  .join('\n')}
`
  )
  .join('\n')}

# ------------------------------------------------------------------------------
# 3. CACHING LAYER (Amazon ElastiCache Redis Cluster)
# ------------------------------------------------------------------------------
${arch.cacheNodes
  .filter(c => c.enabled)
  .map(
    cache => `
resource "aws_elasticache_replication_group" "${cache.id.replace(/-/g, '_')}_cluster" {
  replication_group_id          = "${cache.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}"
  replication_group_description = "Managed Redis Cache Cluster for InfraWeave"
  node_type                     = "${cache.ramGbPerNode >= 32 ? 'cache.r6g.xlarge' : 'cache.m6g.large'}"
  num_cache_clusters            = ${cache.nodes}
  automatic_failover_enabled    = ${cache.nodes > 1}
  multi_az_enabled              = ${cache.nodes > 1}
  port                          = 6379
  at_rest_encryption_enabled    = true
  transit_encryption_enabled    = true
}
`
  )
  .join('\n')}
`;
}

export function generateKubernetesYaml(arch: InfrastructureArchitecture): string {
  return `# ==============================================================================
# Kubernetes Manifests - Generated by InfraWeave
# Topology: ${arch.name}
# ==============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: infraweave-production
---
${arch.computeNodes
  .map(
    comp => `
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${comp.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}
  namespace: infraweave-production
  labels:
    app.kubernetes.io/name: ${comp.id}
    app.kubernetes.io/tier: ${comp.role}
spec:
  replicas: ${comp.instances}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ${comp.id}
  template:
    metadata:
      labels:
        app: ${comp.id}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ${comp.id}
                topologyKey: topology.kubernetes.io/zone
      containers:
        - name: service
          image: ghcr.io/infraweave/runtime:latest
          resources:
            requests:
              cpu: "${Math.max(1, comp.vCpuPerInstance / 2)}000m"
              memory: "${Math.max(2, comp.ramGbPerInstance / 2)}Gi"
            limits:
              cpu: "${comp.vCpuPerInstance}000m"
              memory: "${comp.ramGbPerInstance}Gi"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ${comp.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}-svc
  namespace: infraweave-production
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ${comp.id}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${comp.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}-hpa
  namespace: infraweave-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${comp.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}
  minReplicas: ${Math.max(2, Math.floor(comp.instances * 0.75))}
  maxReplicas: ${Math.ceil(comp.instances * 2.5)}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
`
  )
  .join('\n---\n')}
`;
}

export function generateAdrRecord(
  arch: InfrastructureArchitecture,
  sim: SimulationResult,
  customTitle?: string
): ArchitectureDecisionRecord {
  return {
    id: `ADR-${Math.floor(100 + Math.random() * 900)}`,
    title: customTitle || `Adopt ${arch.name} Architecture Configuration`,
    status: 'Accepted',
    author: 'Staff Infrastructure Architect',
    date: '2026-10-06',
    context: `The platform serves an ingress traffic volume of ${arch.traffic.ingressRps.toLocaleString()} RPS (${(arch.traffic.readWriteRatio * 100).toFixed(0)}% reads). Decisions must reconcile latency SLOs (<${(sim.performance.p95LatencyMs * 1.5).toFixed(0)}ms), composite availability (target >= ${sim.reliability.sloTargetPct}%), and rack power thermal budgets (<12 kW/rack).`,
    decision: `We selected ${arch.name} with ${arch.computeNodes.reduce((a, c) => a + c.instances, 0)} compute units, ${arch.databaseNodes.reduce((a, d) => a + d.readReplicas, 0)} read replicas in ${arch.databaseNodes[0]?.replicationMode || 'async'} mode, and active caching with ${arch.cacheNodes[0]?.hitRateTarget ? (arch.cacheNodes[0].hitRateTarget * 100).toFixed(0) : 0}% target hit rate.`,
    consequences: {
      positive: [
        `Achieves composite availability of ${sim.reliability.compositeAvailabilityPct}% (${sim.reliability.availabilityNines} nines).`,
        `Maintains p95 end-to-end latency at ${sim.performance.p95LatencyMs}ms with Little's Law queue delay of ${sim.performance.queueingDelayMs}ms.`,
        `Comfortable safety margin with ${sim.capacity.cpuHeadroomPct}% CPU headroom and ${sim.capacity.iopsHeadroomPct}% IOPS headroom.`,
      ],
      negative: [
        `Committed cloud infrastructure budget of $${sim.cost.monthlyTotal.toLocaleString()}/month ($${sim.cost.annualTotal.toLocaleString()}/year).`,
        `Data center IT power dissipation of ${sim.dataCenter.itPowerDrawKw} kW (${sim.dataCenter.totalBtuPerHour.toLocaleString()} BTU/hr heat generation).`,
      ],
      neutral: [
        `Failover MTTR is approximately ${sim.reliability.mttrMinutes} minutes via automated health-check re-routing.`,
        `Requires periodic audit of replica lag and cache eviction eviction policies.`,
      ],
    },
    metricsEvidence: {
      monthlyCost: `$${sim.cost.monthlyTotal.toLocaleString()}/mo`,
      p95Latency: `${sim.performance.p95LatencyMs} ms`,
      availability: `${sim.reliability.compositeAvailabilityPct}%`,
      powerKw: `${sim.dataCenter.itPowerDrawKw} kW`,
    },
  };
}
