import { InfrastructureArchitecture } from '../types/infrastructure';

export const ARCHITECTURE_PRESETS: Record<string, InfrastructureArchitecture> = {
  'ecommerce-scale': {
    id: 'arch-ecommerce-scale',
    name: 'E-Commerce Peak (Global Scale)',
    description: 'High-availability e-commerce platform with Redis read caching, distributed DB replicas, and dual-rack distribution.',
    createdAt: '2026-10-01T10:00:00Z',
    updatedAt: '2026-10-06T20:30:00Z',
    regions: [
      {
        id: 'reg-us-east',
        name: 'US East (N. Virginia)',
        code: 'us-east-1',
        gridPowerCostKwh: 0.115,
        carbonGramsKwh: 340,
        ambientTempC: 22,
      },
      {
        id: 'reg-eu-west',
        name: 'Europe West (Frankfurt)',
        code: 'eu-west-1',
        gridPowerCostKwh: 0.22,
        carbonGramsKwh: 180,
        ambientTempC: 19,
      },
    ],
    coolingZones: [
      {
        id: 'cool-zone-1',
        regionId: 'reg-us-east',
        name: 'Zone A Chilled Water Loop',
        maxCoolingTons: 25,
        coolingType: 'chilled-water',
        targetPue: 1.22,
      },
      {
        id: 'cool-zone-2',
        regionId: 'reg-eu-west',
        name: 'Zone B Direct Air Economizer',
        maxCoolingTons: 20,
        coolingType: 'direct-air-free',
        targetPue: 1.15,
      },
    ],
    racks: [
      {
        id: 'rack-a1',
        code: 'Rack-A1 (US-East)',
        regionId: 'reg-us-east',
        coolingZoneId: 'cool-zone-1',
        maxPowerKw: 12.5,
        pduRedundancy: 'dual-A/B',
        totalUHeight: 42,
      },
      {
        id: 'rack-a2',
        code: 'Rack-A2 (US-East)',
        regionId: 'reg-us-east',
        coolingZoneId: 'cool-zone-1',
        maxPowerKw: 12.5,
        pduRedundancy: 'dual-A/B',
        totalUHeight: 42,
      },
      {
        id: 'rack-b1',
        code: 'Rack-B1 (EU-West)',
        regionId: 'reg-eu-west',
        coolingZoneId: 'cool-zone-2',
        maxPowerKw: 10.0,
        pduRedundancy: 'dual-A/B',
        totalUHeight: 42,
      },
    ],
    computeNodes: [
      {
        id: 'comp-api-us',
        name: 'API Gateway Pool',
        role: 'api',
        vCpuPerInstance: 8,
        ramGbPerInstance: 16,
        instances: 6,
        unitCostPerHour: 0.384,
        powerWattsPerUnit: 280,
        maxQpsPerInstance: 3500,
        rackId: 'rack-a1',
        regionId: 'reg-us-east',
      },
      {
        id: 'comp-worker-us',
        name: 'Async Order Workers',
        role: 'worker',
        vCpuPerInstance: 4,
        ramGbPerInstance: 8,
        instances: 4,
        unitCostPerHour: 0.192,
        powerWattsPerUnit: 180,
        maxQpsPerInstance: 1500,
        rackId: 'rack-a2',
        regionId: 'reg-us-east',
      },
    ],
    databaseNodes: [
      {
        id: 'db-postgres-core',
        name: 'Primary Aurora PostgreSQL',
        engine: 'postgres',
        primaryInstances: 1,
        readReplicas: 2,
        storageGb: 800,
        iopsProvisioned: 8000,
        unitCostPerHour: 0.86,
        maxReadQps: 6000,
        maxWriteQps: 2800,
        replicationMode: 'async',
        replicationLagMs: 25,
        powerWatts: 450,
        rackId: 'rack-a1',
        regionId: 'reg-us-east',
      },
    ],
    cacheNodes: [
      {
        id: 'cache-redis-cluster',
        name: 'Redis Distributed Cache',
        engine: 'redis',
        nodes: 3,
        ramGbPerNode: 24,
        unitCostPerHour: 0.24,
        hitRateTarget: 0.88,
        powerWatts: 140,
        rackId: 'rack-a2',
        regionId: 'reg-us-east',
        enabled: true,
      },
    ],
    queueNodes: [
      {
        id: 'queue-kafka-events',
        name: 'Kafka Checkout Bus',
        engine: 'kafka',
        partitions: 12,
        throughputMsgPerSec: 25000,
        retentionHours: 72,
        unitCostPerHour: 0.45,
        powerWatts: 300,
        rackId: 'rack-a2',
        regionId: 'reg-us-east',
      },
    ],
    storageNodes: [
      {
        id: 'store-product-media',
        name: 'S3 Product Assets',
        type: 'object-s3',
        sizeTb: 18,
        egressGbPerMonth: 6500,
        costPerGbMonth: 0.023,
        durabilityNines: 11,
        powerWatts: 80,
        regionId: 'reg-us-east',
      },
    ],
    links: [
      {
        id: 'link-api-cache',
        sourceId: 'comp-api-us',
        targetId: 'cache-redis-cluster',
        bandwidthGbps: 25,
        baselineLatencyMs: 0.8,
        packetLossPct: 0.001,
        egressCostPerGb: 0,
        crossRegion: false,
      },
      {
        id: 'link-api-db',
        sourceId: 'comp-api-us',
        targetId: 'db-postgres-core',
        bandwidthGbps: 25,
        baselineLatencyMs: 1.2,
        packetLossPct: 0.001,
        egressCostPerGb: 0,
        crossRegion: false,
      },
      {
        id: 'link-api-queue',
        sourceId: 'comp-api-us',
        targetId: 'queue-kafka-events',
        bandwidthGbps: 10,
        baselineLatencyMs: 1.1,
        packetLossPct: 0.001,
        egressCostPerGb: 0,
        crossRegion: false,
      },
    ],
    traffic: {
      ingressRps: 14500,
      readWriteRatio: 0.85,
      payloadSizeKb: 4.8,
      burstMultiplier: 1.0,
      trafficPattern: 'steady',
      geoDistribution: {
        'reg-us-east': 0.7,
        'reg-eu-west': 0.3,
      },
    },
  },

  'financial-core': {
    id: 'arch-financial-core',
    name: 'Multi-Region Financial Core (Zero-RPO)',
    description: 'Active-active financial transaction processing engine with synchronous replication across transatlantic zones.',
    createdAt: '2026-10-02T14:00:00Z',
    updatedAt: '2026-10-06T18:00:00Z',
    regions: [
      {
        id: 'reg-us-east',
        name: 'US East (New York Financial Cloud)',
        code: 'us-east-1',
        gridPowerCostKwh: 0.14,
        carbonGramsKwh: 310,
        ambientTempC: 21,
      },
      {
        id: 'reg-eu-west',
        name: 'EU West (London Equinix LD4)',
        code: 'eu-west-1',
        gridPowerCostKwh: 0.26,
        carbonGramsKwh: 160,
        ambientTempC: 18,
      },
    ],
    coolingZones: [
      {
        id: 'cool-zone-ny',
        regionId: 'reg-us-east',
        name: 'NY Liquid Submersion Pod',
        maxCoolingTons: 40,
        coolingType: 'chilled-water',
        targetPue: 1.18,
      },
      {
        id: 'cool-zone-ld4',
        regionId: 'reg-eu-west',
        name: 'LD4 Cold Aisle Containment',
        maxCoolingTons: 35,
        coolingType: 'hot-aisle-containment',
        targetPue: 1.20,
      },
    ],
    racks: [
      {
        id: 'rack-fin-ny1',
        code: 'Rack-NY1-TierIV',
        regionId: 'reg-us-east',
        coolingZoneId: 'cool-zone-ny',
        maxPowerKw: 15.0,
        pduRedundancy: 'dual-A/B',
        totalUHeight: 42,
      },
      {
        id: 'rack-fin-ld1',
        code: 'Rack-LD1-TierIV',
        regionId: 'reg-eu-west',
        coolingZoneId: 'cool-zone-ld4',
        maxPowerKw: 15.0,
        pduRedundancy: 'dual-A/B',
        totalUHeight: 42,
      },
    ],
    computeNodes: [
      {
        id: 'comp-fin-ny',
        name: 'Ledger Gateway NY',
        role: 'api',
        vCpuPerInstance: 16,
        ramGbPerInstance: 32,
        instances: 8,
        unitCostPerHour: 0.768,
        powerWattsPerUnit: 380,
        maxQpsPerInstance: 5000,
        rackId: 'rack-fin-ny1',
        regionId: 'reg-us-east',
      },
      {
        id: 'comp-fin-ld',
        name: 'Ledger Gateway London',
        role: 'api',
        vCpuPerInstance: 16,
        ramGbPerInstance: 32,
        instances: 8,
        unitCostPerHour: 0.812,
        powerWattsPerUnit: 380,
        maxQpsPerInstance: 5000,
        rackId: 'rack-fin-ld1',
        regionId: 'reg-eu-west',
      },
    ],
    databaseNodes: [
      {
        id: 'db-spanner-core',
        name: 'Global Distributed Spanner',
        engine: 'spanner',
        primaryInstances: 2,
        readReplicas: 3,
        storageGb: 2400,
        iopsProvisioned: 24000,
        unitCostPerHour: 2.15,
        maxReadQps: 18000,
        maxWriteQps: 9000,
        replicationMode: 'sync',
        replicationLagMs: 8,
        powerWatts: 650,
        rackId: 'rack-fin-ny1',
        regionId: 'reg-us-east',
      },
    ],
    cacheNodes: [
      {
        id: 'cache-fin-redis',
        name: 'In-Memory State Store',
        engine: 'redis',
        nodes: 4,
        ramGbPerNode: 64,
        unitCostPerHour: 0.48,
        hitRateTarget: 0.92,
        powerWatts: 180,
        rackId: 'rack-fin-ny1',
        regionId: 'reg-us-east',
        enabled: true,
      },
    ],
    queueNodes: [
      {
        id: 'queue-fin-audit',
        name: 'Regulatory Audit Ledger Bus',
        engine: 'kafka',
        partitions: 24,
        throughputMsgPerSec: 50000,
        retentionHours: 8760, // 1 year compliance
        unitCostPerHour: 0.92,
        powerWatts: 420,
        rackId: 'rack-fin-ny1',
        regionId: 'reg-us-east',
      },
    ],
    storageNodes: [
      {
        id: 'store-immutable-wal',
        name: 'WORM Immutable Archive',
        type: 'cold-archive',
        sizeTb: 120,
        egressGbPerMonth: 200,
        costPerGbMonth: 0.004,
        durabilityNines: 11,
        powerWatts: 120,
        regionId: 'reg-us-east',
      },
    ],
    links: [
      {
        id: 'link-cross-atlantic',
        sourceId: 'comp-fin-ny',
        targetId: 'comp-fin-ld',
        bandwidthGbps: 100,
        baselineLatencyMs: 34.0,
        packetLossPct: 0.0001,
        egressCostPerGb: 0.02,
        crossRegion: true,
      },
    ],
    traffic: {
      ingressRps: 22000,
      readWriteRatio: 0.65,
      payloadSizeKb: 2.1,
      burstMultiplier: 1.0,
      trafficPattern: 'steady',
      geoDistribution: {
        'reg-us-east': 0.55,
        'reg-eu-west': 0.45,
      },
    },
  },

  'ai-inference': {
    id: 'arch-ai-inference',
    name: 'Real-Time AI Inference Pipeline',
    description: 'GPU-accelerated vector search and token generation cluster with low-latency KV caches.',
    createdAt: '2026-10-04T08:00:00Z',
    updatedAt: '2026-10-06T19:15:00Z',
    regions: [
      {
        id: 'reg-us-west',
        name: 'US West (Oregon Renewable)',
        code: 'us-west-2',
        gridPowerCostKwh: 0.082,
        carbonGramsKwh: 95,
        ambientTempC: 17,
      },
    ],
    coolingZones: [
      {
        id: 'cool-zone-hydro',
        regionId: 'reg-us-west',
        name: 'Hydro-Direct Rear Door Exchanger',
        maxCoolingTons: 60,
        coolingType: 'hot-aisle-containment',
        targetPue: 1.12,
      },
    ],
    racks: [
      {
        id: 'rack-gpu-1',
        code: 'Rack-GPU-HighDensity',
        regionId: 'reg-us-west',
        coolingZoneId: 'cool-zone-hydro',
        maxPowerKw: 24.0, // High density GPU rack
        pduRedundancy: 'dual-A/B',
        totalUHeight: 42,
      },
    ],
    computeNodes: [
      {
        id: 'comp-gpu-inference',
        name: 'H100/L40S Inference Cluster',
        role: 'ml-inference',
        vCpuPerInstance: 32,
        ramGbPerInstance: 128,
        instances: 8,
        unitCostPerHour: 3.45,
        powerWattsPerUnit: 1400,
        maxQpsPerInstance: 850,
        rackId: 'rack-gpu-1',
        regionId: 'reg-us-west',
      },
    ],
    databaseNodes: [
      {
        id: 'db-vector-pgvector',
        name: 'PgVector Embeddings Index',
        engine: 'postgres',
        primaryInstances: 1,
        readReplicas: 2,
        storageGb: 1500,
        iopsProvisioned: 12000,
        unitCostPerHour: 1.25,
        maxReadQps: 7500,
        maxWriteQps: 1800,
        replicationMode: 'async',
        replicationLagMs: 14,
        powerWatts: 500,
        rackId: 'rack-gpu-1',
        regionId: 'reg-us-west',
      },
    ],
    cacheNodes: [
      {
        id: 'cache-kv-redis',
        name: 'Prefix & KV Cache Store',
        engine: 'redis',
        nodes: 4,
        ramGbPerNode: 64,
        unitCostPerHour: 0.52,
        hitRateTarget: 0.78,
        powerWatts: 200,
        rackId: 'rack-gpu-1',
        regionId: 'reg-us-west',
        enabled: true,
      },
    ],
    queueNodes: [
      {
        id: 'queue-prompt-requests',
        name: 'Streaming Prompt Queue',
        engine: 'kafka',
        partitions: 16,
        throughputMsgPerSec: 15000,
        retentionHours: 24,
        unitCostPerHour: 0.65,
        powerWatts: 350,
        rackId: 'rack-gpu-1',
        regionId: 'reg-us-west',
      },
    ],
    storageNodes: [
      {
        id: 'store-model-weights',
        name: 'NVMe Model Checkpoint Store',
        type: 'block-ebs',
        sizeTb: 12,
        egressGbPerMonth: 800,
        costPerGbMonth: 0.08,
        durabilityNines: 6,
        powerWatts: 150,
        regionId: 'reg-us-west',
      },
    ],
    links: [],
    traffic: {
      ingressRps: 4200,
      readWriteRatio: 0.92,
      payloadSizeKb: 14.5,
      burstMultiplier: 1.0,
      trafficPattern: 'bursty',
      geoDistribution: {
        'reg-us-west': 1.0,
      },
    },
  },

  'lean-startup': {
    id: 'arch-lean-startup',
    name: 'Lean SaaS MVP (Cost-Constrained)',
    description: 'Single-node deployment with monolithic database and zero redundancy. Highly economical but high SPOF risk.',
    createdAt: '2026-10-05T12:00:00Z',
    updatedAt: '2026-10-06T15:00:00Z',
    regions: [
      {
        id: 'reg-us-central',
        name: 'US Central (Iowa)',
        code: 'us-central1',
        gridPowerCostKwh: 0.098,
        carbonGramsKwh: 420,
        ambientTempC: 23,
      },
    ],
    coolingZones: [
      {
        id: 'cool-zone-shared',
        regionId: 'reg-us-central',
        name: 'Standard Shared Floor',
        maxCoolingTons: 10,
        coolingType: 'chilled-water',
        targetPue: 1.35,
      },
    ],
    racks: [
      {
        id: 'rack-mvp-1',
        code: 'Rack-MVP-1',
        regionId: 'reg-us-central',
        coolingZoneId: 'cool-zone-shared',
        maxPowerKw: 8.0,
        pduRedundancy: 'single',
        totalUHeight: 42,
      },
    ],
    computeNodes: [
      {
        id: 'comp-monolith',
        name: 'App Monolith (Node.js)',
        role: 'api',
        vCpuPerInstance: 4,
        ramGbPerInstance: 8,
        instances: 1, // Single instance SPOF!
        unitCostPerHour: 0.16,
        powerWattsPerUnit: 140,
        maxQpsPerInstance: 1800,
        rackId: 'rack-mvp-1',
        regionId: 'reg-us-central',
      },
    ],
    databaseNodes: [
      {
        id: 'db-single-postgres',
        name: 'Standalone PostgreSQL',
        engine: 'postgres',
        primaryInstances: 1,
        readReplicas: 0, // No replicas SPOF!
        storageGb: 100,
        iopsProvisioned: 1500,
        unitCostPerHour: 0.18,
        maxReadQps: 1500,
        maxWriteQps: 800,
        replicationMode: 'async',
        replicationLagMs: 0,
        powerWatts: 160,
        rackId: 'rack-mvp-1',
        regionId: 'reg-us-central',
      },
    ],
    cacheNodes: [
      {
        id: 'cache-mvp-redis',
        name: 'Single Redis Instance',
        engine: 'redis',
        nodes: 1,
        ramGbPerNode: 4,
        unitCostPerHour: 0.06,
        hitRateTarget: 0.70,
        powerWatts: 50,
        rackId: 'rack-mvp-1',
        regionId: 'reg-us-central',
        enabled: false, // Disabled to save cost!
      },
    ],
    queueNodes: [],
    storageNodes: [
      {
        id: 'store-app-uploads',
        name: 'Standard Object Bucket',
        type: 'object-s3',
        sizeTb: 0.8,
        egressGbPerMonth: 300,
        costPerGbMonth: 0.023,
        durabilityNines: 11,
        powerWatts: 20,
        regionId: 'reg-us-central',
      },
    ],
    links: [],
    traffic: {
      ingressRps: 1200,
      readWriteRatio: 0.8,
      payloadSizeKb: 3.2,
      burstMultiplier: 1.0,
      trafficPattern: 'steady',
      geoDistribution: {
        'reg-us-central': 1.0,
      },
    },
  },
};
